// Slide deck logic for the window mode panel.
//
// Plan/slides.md defines the deck and the rules around dynamic
// visibility ("moon-phase slide and special-events slide can appear /
// disappear; the currently-viewed slide does not shift when others
// appear / disappear") and looping wrap ("right at last → first; left at
// first → last; same-direction wrap, no reverse-spin").
//
// The "no reverse-spin" rule is a *visual* concern handled in the
// SlideDeck component (rotateY direction follows the arrow click); this
// module only exposes the index math.
//
// M8: events expand from a single boolean ("show events slide?") to an
// arbitrary list of event-specific slides (one per active event). The
// SlideId type is therefore a discriminated union — static IDs for the
// fixed slides plus a templated `event:*` form supplied by the events
// activation logic.

export type StaticSlideId =
  | 'today'
  | 'seven-day'
  | 'current'
  | 'moon'
  | 'settings';

/**
 * Per-event slide id. Generated by computeActiveEvents in
 * shared/special-events.ts — opaque from the slide-deck's perspective,
 * the deck only needs the ordered list to lay out faces and dots.
 */
export type EventSlideId = `event:${string}`;

/**
 * Per-alert slide id. Built by alertSlideId() in shared/alerts.ts.
 */
export type AlertSlideId = `alert:${string}`;

export type SlideId = StaticSlideId | EventSlideId | AlertSlideId;

// Canonical ordering of the static slides. Event slides slot in between
// `moon` and `settings` (or between `current` and `settings` when moon
// is disabled).
const STATIC_ORDER: readonly StaticSlideId[] = [
  'today',
  'seven-day',
  'current',
  'moon',
  'settings',
] as const;

export type VisibilityFlags = {
  moonEnabled: boolean;
  /**
   * Ordered list of event slide IDs — already sorted today-first then
   * alphabetical-by-type by computeActiveEvents. The deck preserves
   * this order verbatim.
   */
  eventSlideIds: readonly EventSlideId[];
  /**
   * Ordered list of alert slide IDs — already sorted most-urgent-first
   * by sortAlerts. Empty when there are no alerts, the fetch failed, or
   * the location is outside Environment Canada's coverage.
   */
  alertSlideIds?: readonly AlertSlideId[];
  /**
   * True when at least one active alert is a full `warning`. Promotes
   * the whole alert group to the front of the deck — see
   * plan/slides.md § Severe weather alerts. Promotion changes where
   * the slides sit, never what the user is currently looking at:
   * reconcileCurrentSlideIndex tracks slide *ids*, so re-ordering
   * around the viewer is invisible to them.
   */
  alertsPromoted?: boolean;
};

export function computeVisibleSlides(flags: VisibilityFlags): SlideId[] {
  const out: SlideId[] = [];
  const alertIds = flags.alertSlideIds ?? [];
  const promoted = alertIds.length > 0 && flags.alertsPromoted === true;
  // A warning puts the alert group ahead of everything, including
  // Today. Anything less urgent sits with the special events.
  if (promoted) out.push(...alertIds);
  for (const id of STATIC_ORDER) {
    if (id === 'moon' && !flags.moonEnabled) continue;
    if (id === 'settings') {
      // Splice the event slides in just before settings so settings
      // stays last per plan/slides.md. Un-promoted alerts ride along
      // here, ahead of the events.
      if (!promoted) out.push(...alertIds);
      for (const ev of flags.eventSlideIds) out.push(ev);
      out.push('settings');
      continue;
    }
    out.push(id);
  }
  return out;
}

/**
 * Where the deck should sit after the visible-slide list changes.
 *
 * Normally the reconciled index — the rule that the viewed slide does
 * not shift when others appear or disappear.
 *
 * The exception is a promoted warning arriving before the user has
 * navigated. Opening at index 0 already lands on the alert when the
 * data is in the store, but on a cold start the window opens first and
 * the alerts arrive moments later; reconcile would then keep the user
 * on Today and quietly insert the warning behind them. "Don't move the
 * viewer" exists so we never interrupt someone who is reading, and
 * someone who has not touched the arrows since the window opened is
 * not reading anything yet — so the deck follows the alert forward.
 *
 * Once they navigate, nothing moves them again. See plan/slides.md
 * § Opening slide.
 */
export function resolveDeckIndex(input: {
  visibleSlides: readonly SlideId[];
  reconciledIndex: number;
  alertsPromoted: boolean;
  hasNavigated: boolean;
}): number {
  const { visibleSlides, reconciledIndex, alertsPromoted, hasNavigated } =
    input;
  if (hasNavigated || !alertsPromoted) return reconciledIndex;

  const first = visibleSlides[0];
  // Only a promoted group sits at index 0. A watch or advisory rides
  // with the events and must not change where the deck opens.
  if (first !== undefined && isAlertSlideId(first)) return 0;
  return reconciledIndex;
}

export type WrapDirection = 'next' | 'prev';

export function wrapStep(
  currentIndex: number,
  length: number,
  direction: WrapDirection,
): number {
  if (length <= 0) return 0;
  if (direction === 'next') return (currentIndex + 1) % length;
  return (currentIndex - 1 + length) % length;
}

// When the visible-slide list changes (moon toggled, events become
// active / inactive), keep the user on the slide they were viewing.
// If that slide is no longer visible, fall back to the nearest preceding
// slide that is still in the list — the next-best stable choice that
// preserves "rough position" without jumping the user to slide 0.
export function reconcileCurrentSlideIndex(
  prevVisible: readonly SlideId[],
  prevIndex: number,
  nextVisible: readonly SlideId[],
): number {
  if (nextVisible.length === 0) return 0;
  const currentId = prevVisible[prevIndex];
  if (currentId === undefined) return 0;

  const directHit = nextVisible.indexOf(currentId);
  if (directHit !== -1) return directHit;

  for (let i = prevIndex - 1; i >= 0; i--) {
    const id = prevVisible[i];
    if (id === undefined) continue;
    const idx = nextVisible.indexOf(id);
    if (idx !== -1) return idx;
  }
  return 0;
}

/**
 * True when the slide id is one of the static (always-known) slides —
 * useful in render switches that need to differentiate the four event
 * slide kinds (which are fully data-driven) from the five static slides
 * (which have dedicated components).
 */
export function isAlertSlideId(id: SlideId): id is AlertSlideId {
  return id.startsWith('alert:');
}

export function isStaticSlideId(id: SlideId): id is StaticSlideId {
  return (
    id === 'today' ||
    id === 'seven-day' ||
    id === 'current' ||
    id === 'moon' ||
    id === 'settings'
  );
}
