// Slide deck logic for the window mode panel.
//
// Plan/slides.md defines the deck and the rules around dynamic
// visibility ("moon-phase slide and special-events slide can appear /
// disappear; the currently-viewed slide does not shift when others
// appear / disappear") and looping wrap ("right at last → first; left at
// first → last; same-direction wrap, no reverse-spin").
//
// The "no reverse-spin" rule is a *visual* concern handled in the
// SlideDeck component (rotateY direction follows the arrow click); this
// module only exposes the index math.
//
// M8: events expand from a single boolean ("show events slide?") to an
// arbitrary list of event-specific slides (one per active event). The
// SlideId type is therefore a discriminated union — static IDs for the
// fixed slides plus a templated `event:*` form supplied by the events
// activation logic.

export type StaticSlideId =
  | 'today'
  | 'seven-day'
  | 'current'
  | 'moon'
  | 'settings';

/**
 * Per-event slide id. Generated by computeActiveEvents in
 * shared/special-events.ts — opaque from the slide-deck's perspective,
 * the deck only needs the ordered list to lay out faces and dots.
 */
export type EventSlideId = `event:${string}`;

export type SlideId = StaticSlideId | EventSlideId;

// Canonical ordering of the static slides. Event slides slot in between
// `moon` and `settings` (or between `current` and `settings` when moon
// is disabled).
const STATIC_ORDER: readonly StaticSlideId[] = [
  'today',
  'seven-day',
  'current',
  'moon',
  'settings',
] as const;

export type VisibilityFlags = {
  moonEnabled: boolean;
  /**
   * Ordered list of event slide IDs — already sorted today-first then
   * alphabetical-by-type by computeActiveEvents. The deck preserves
   * this order verbatim.
   */
  eventSlideIds: readonly EventSlideId[];
};

export function computeVisibleSlides(flags: VisibilityFlags): SlideId[] {
  const out: SlideId[] = [];
  for (const id of STATIC_ORDER) {
    if (id === 'moon' && !flags.moonEnabled) continue;
    if (id === 'settings') {
      // Splice the event slides in just before settings so settings
      // stays last per plan/slides.md.
      for (const ev of flags.eventSlideIds) out.push(ev);
      out.push('settings');
      continue;
    }
    out.push(id);
  }
  return out;
}

export type WrapDirection = 'next' | 'prev';

export function wrapStep(
  currentIndex: number,
  length: number,
  direction: WrapDirection,
): number {
  if (length <= 0) return 0;
  if (direction === 'next') return (currentIndex + 1) % length;
  return (currentIndex - 1 + length) % length;
}

// When the visible-slide list changes (moon toggled, events become
// active / inactive), keep the user on the slide they were viewing.
// If that slide is no longer visible, fall back to the nearest preceding
// slide that is still in the list — the next-best stable choice that
// preserves "rough position" without jumping the user to slide 0.
export function reconcileCurrentSlideIndex(
  prevVisible: readonly SlideId[],
  prevIndex: number,
  nextVisible: readonly SlideId[],
): number {
  if (nextVisible.length === 0) return 0;
  const currentId = prevVisible[prevIndex];
  if (currentId === undefined) return 0;

  const directHit = nextVisible.indexOf(currentId);
  if (directHit !== -1) return directHit;

  for (let i = prevIndex - 1; i >= 0; i--) {
    const id = prevVisible[i];
    if (id === undefined) continue;
    const idx = nextVisible.indexOf(id);
    if (idx !== -1) return idx;
  }
  return 0;
}

/**
 * True when the slide id is one of the static (always-known) slides —
 * useful in render switches that need to differentiate the four event
 * slide kinds (which are fully data-driven) from the five static slides
 * (which have dedicated components).
 */
export function isStaticSlideId(id: SlideId): id is StaticSlideId {
  return (
    id === 'today' ||
    id === 'seven-day' ||
    id === 'current' ||
    id === 'moon' ||
    id === 'settings'
  );
}
